In [1]:
## Import dependencies
import pandas as pd
import numpy as np
import requests 
import matplotlib as plt
import plotly.express as px

In [2]:
# Read in CSV files as Pandas DataFrames.
netflix1_df = pd.read_csv('../Netflix_Team_1/Resources/netflix_list.csv', low_memory=False)
netflix2_df = pd.read_csv('../Netflix_Team_1/Resources/netflix_titles.csv', low_memory=False)

In [3]:
netflix1_df

,imdb_id,title,popular_rank,certificate,startYear,endYear,episodes,runtime,type,orign_country,language,plot,summary,rating,numVotes,genres,isAdult,cast,image_url
0,tt4052886,Lucifer,1,15,2016.0,NaN,93.0,42,tvSeries,United States,English,Lucifer Morningstar has decided he's had enoug...,"Lucifer Morningstar, bored from his sulking li...",8.1,250884.0,"Crime,Drama,Fantasy",0,"['Tom Ellis', 'Lauren German', 'Lesley-Ann Bra...",https://m.media-amazon.com/images/M/MV5BNzY1Yj...
1,tt0993840,Army of the Dead,2,18,2021.0,NaN,NaN,148,movie,United States,English,"Following a zombie outbreak in Las Vegas, a gr...","With the abandoned, walled city of Las Vegas o...",5.8,110780.0,"Action,Crime,Horror",0,"['Dave Bautista', 'Ella Purnell', 'Ana de la R...",https://m.media-amazon.com/images/M/MV5BNGY0Nz...
2,tt7255502,The Kominsky Method,3,18,2018.0,2021.0,22.0,30,tvSeries,United States,English,"An aging actor, who long ago enjoyed a brush w...",Michael Douglas plays an actor who made it big...,8.2,28795.0,"Comedy,Drama",0,"['Michael Douglas', 'Sarah Baker', 'Graham Rog...",https://m.media-amazon.com/images/M/MV5BMzA0YT...
3,tt0108778,Friends,4,13+,1994.0,2004.0,235.0,22,tvSeries,United States,English,Follows the personal and professional lives of...,"Ross Geller, Rachel Green, Monica Geller, Joey...",8.9,861843.0,"Comedy,Romance",0,"['Jennifer Aniston', 'Courteney Cox', 'Lisa Ku...",https://m.media-amazon.com/images/M/MV5BNDVkYj...
4,tt9251798,Ragnarok,5,18,2020.0,NaN,12.0,45,tvSeries,Norway,Norwegian,A small Norwegian town experiencing warm winte...,In the small fictional town of Edda coming of ...,7.5,26606.0,"Action,Drama,Fantasy",0,"['David Stakston', 'Jonas Strand Gravli', 'Her...",https://m.media-amazon.com/images/M/MV5BODM3NT...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7003,tt9777386,Merry Happy Whatever,"16,543",13,2019.0,NaN,NaN,28,tvEpisode,United States,English,When his daughter arrives home for the holiday...,When his daughter arrives home for the holiday...,6.1,221.0,Comedy,0,"['Dennis Quaid', 'Bridgit Mendler', 'Brent Mor...",https://m.media-amazon.com/images/M/MV5BOTc0ND...
7004,tt9790434,The Morning Show,"16,569",NaN,2019.0,NaN,NaN,30,tvEpisode,-,-,NaN,-,NaN,NaN,\N,0,"['Bounty Hunters Brothers', 'Bruce Lourie', 'C...",https://m.media-amazon.com/images/G/01/imdb/im...
7005,tt9817600,Losers,"16,599",16,2019.0,NaN,NaN,\N,tvEpisode,-,-,"The life of Michael Bentt, a champion boxer fo...","The life of Michael Bentt, a champion boxer fo...",8.0,221.0,"Documentary,Sport",0,"['Michael Bentt', 'Harold Perrineau', 'Mickey ...",https://m.media-amazon.com/images/M/MV5BOTY3Zj...
7006,tt9842922,Firefly Lane,"16,627",18,2021.0,NaN,NaN,51,tvEpisode,United States,English,Kate experiences the force of nature that is T...,Kate experiences the force of nature that is T...,7.3,380.0,"Drama,Romance",0,"['Katherine Heigl', 'Sarah Chalke', 'Ben Lawso...",https://m.media-amazon.com/images/M/MV5BODM3OW...
7007,tt9865968,Medical Police,"16,648",NaN,2020.0,NaN,NaN,25,tvEpisode,United States,English,NaN,-,6.6,133.0,Comedy,0,"['Erinn Hayes', 'Rob Huebel', 'Edwin Colón', '...",https://m.media-amazon.com/images/M/MV5BZTU5NT...

In [4]:
#Drop unused Columns
netflix1_df_dropped = netflix1_df.drop(columns=['imdb_id','popular_rank','certificate','episodes','endYear','plot','summary','isAdult','image_url','cast'])
netflix1_df_dropped.head()

,title,startYear,runtime,type,orign_country,language,rating,numVotes,genres
0,Lucifer,2016.0,42,tvSeries,United States,English,8.1,250884.0,"Crime,Drama,Fantasy"
1,Army of the Dead,2021.0,148,movie,United States,English,5.8,110780.0,"Action,Crime,Horror"
2,The Kominsky Method,2018.0,30,tvSeries,United States,English,8.2,28795.0,"Comedy,Drama"
3,Friends,1994.0,22,tvSeries,United States,English,8.9,861843.0,"Comedy,Romance"
4,Ragnarok,2020.0,45,tvSeries,Norway,Norwegian,7.5,26606.0,"Action,Drama,Fantasy"

In [5]:
#Check for null columns
netflix1_df_dropped.isnull().sum()

title               0
startYear         515
runtime             2
type                2
orign_country       0
language            0
rating           1008
numVotes         1008
genres              2
dtype: int64

In [6]:
#Count of total number of values in each column
netflix1_df_dropped.count()

title            7008
startYear        6493
runtime          7006
type             7006
orign_country    7008
language         7008
rating           6000
numVotes         6000
genres           7006
dtype: int64

In [7]:
#Look at missing data
netflix1_df_dropped[netflix1_df_dropped['runtime'].isnull()]

,title,startYear,runtime,type,orign_country,language,rating,numVotes,genres
6624,The War Next-Door,NaN,NaN,NaN,Mexico,Spanish,NaN,NaN,NaN
6625,Exception,NaN,NaN,NaN,-,-,NaN,NaN,NaN

In [8]:
#Look at missing data
netflix1_df_dropped[netflix1_df_dropped['genres'].isnull()]

,title,startYear,runtime,type,orign_country,language,rating,numVotes,genres
6624,The War Next-Door,NaN,NaN,NaN,Mexico,Spanish,NaN,NaN,NaN
6625,Exception,NaN,NaN,NaN,-,-,NaN,NaN,NaN

In [9]:
#Look at missing data
netflix1_df_dropped[netflix1_df_dropped['rating'].isnull()]

,title,startYear,runtime,type,orign_country,language,rating,numVotes,genres
152,Don't Look Up,2021.0,\N,movie,United States,English,NaN,NaN,Comedy
167,Hotel Transylvania: Transformania,2021.0,\N,movie,United States,English,NaN,NaN,"Adventure,Animation,Comedy"
173,The Sandman,2021.0,\N,tvSeries,United States,English,NaN,NaN,"Action,Adventure,Drama"
251,Army of the Dead: Lost Vegas,2021.0,\N,tvSeries,United States,English,NaN,NaN,"Action,Animation,Crime"
289,The Ice Road,2021.0,103,movie,United States,English,NaN,NaN,Thriller
...,...,...,...,...,...,...,...,...,...
6975,Ponysitters Club,2018.0,\N,tvEpisode,Canada,English,NaN,NaN,Family
6979,Maya and the Three,2021.0,\N,tvEpisode,United States,English,NaN,NaN,"Action,Adventure,Animation"
6984,Cowboy Bebop,2021.0,\N,tvEpisode,United States,English,NaN,NaN,"Action,Adventure,Crime"
7001,Pieces of Her,2021.0,\N,tvEpisode,United States,English,NaN,NaN,"Drama,Thriller"
7004,The Morning Show,2019.0,30,tvEpisode,-,-,NaN,NaN,\N

In [10]:
#Drop rows with missing data
netflix1_df_dropped_data = netflix1_df_dropped.dropna(subset=['rating','genres','runtime','type'])
netflix1_df_dropped_data

,title,startYear,runtime,type,orign_country,language,rating,numVotes,genres
0,Lucifer,2016.0,42,tvSeries,United States,English,8.1,250884.0,"Crime,Drama,Fantasy"
1,Army of the Dead,2021.0,148,movie,United States,English,5.8,110780.0,"Action,Crime,Horror"
2,The Kominsky Method,2018.0,30,tvSeries,United States,English,8.2,28795.0,"Comedy,Drama"
3,Friends,1994.0,22,tvSeries,United States,English,8.9,861843.0,"Comedy,Romance"
4,Ragnarok,2020.0,45,tvSeries,Norway,Norwegian,7.5,26606.0,"Action,Drama,Fantasy"
...,...,...,...,...,...,...,...,...,...
7002,Ares,2020.0,32,tvEpisode,Netherlands,Dutch,6.5,191.0,"Drama,Horror,Mystery"
7003,Merry Happy Whatever,2019.0,28,tvEpisode,United States,English,6.1,221.0,Comedy
7005,Losers,2019.0,\N,tvEpisode,-,-,8.0,221.0,"Documentary,Sport"
7006,Firefly Lane,2021.0,51,tvEpisode,United States,English,7.3,380.0,"Drama,Romance"
7007,Medical Police,2020.0,25,tvEpisode,United States,English,6.6,133.0,Comedy

In [11]:
#Check for null columns
netflix1_df_dropped_data.isnull().sum()

title            0
startYear        0
runtime          0
type             0
orign_country    0
language         0
rating           0
numVotes         0
genres           0
dtype: int64

In [12]:
#Check and view all Origin Countries
all_orign_countries = dict(netflix1_df_dropped_data['orign_country'].value_counts())
print(all_orign_countries)

{'United States': 2467, 'United Kingdom': 468, 'Japan': 384, 'South Korea': 295, '-': 232, 'India': 221, 'Canada': 194, 'France': 169, 'Spain': 164, 'Mexico': 118, 'Netherlands': 103, 'Italy': 85, 'Germany': 80, 'Brazil': 74, 'Australia': 72, 'China': 70, 'Sweden': 64, 'Argentina': 62, 'Thailand': 59, 'Turkey': 58, 'Indonesia': 48, 'Taiwan': 35, 'Nigeria': 32, 'Poland': 31, 'Colombia': 30, 'Egypt': 29, 'South Africa': 26, 'Denmark': 22, 'Ireland': 21, 'Norway': 21, 'Philippines': 21, 'Romania': 20, 'Belgium': 20, 'Hong Kong': 17, 'Israel': 16, 'Chile': 14, 'Malaysia': 14, 'Russia': 13, 'New Zealand': 12, 'United Arab Emirates': 10, 'Finland': 10, 'Singapore': 7, 'Austria': 7, 'Uruguay': 7, 'Hungary': 6, 'Saudi Arabia': 6, 'Iceland': 5, 'Peru': 5, 'Czech Republic': 5, 'Pakistan': 5, 'Lebanon': 4, 'Vietnam': 3, 'Bulgaria': 3, 'Tunisia': 3, 'Ghana': 3, 'Mauritius': 2, 'Korea': 2, 'Switzerland': 2, 'Georgia': 2, 'Costa Rica': 2, 'Luxembourg': 2, 'Cambodia': 1, 'Venezuela': 1, 'Belarus': 1, 'Moldova': 1, 'Bahamas': 1, 'Portugal': 1, 'Kuwait': 1, 'Occupied Palestinian Territory': 1, 'Cyprus': 1, 'Senegal': 1, 'Paraguay': 1, 'Greece': 1, 'Croatia': 1, 'Jordan': 1, 'Cameroon': 1, 'Iraq': 1, 'Puerto Rico': 1, 'Albania': 1}

In [13]:
#Look for the string "-" as Origin Country
netflix1_df_dropped_data[netflix1_df_dropped_data['orign_country'].str.contains('-')]

,title,startYear,runtime,type,orign_country,language,rating,numVotes,genres
87,Agents of S.H.I.E.L.D.,2013.0,45,tvSeries,-,-,7.5,203431.0,"Action,Adventure,Drama"
360,Full House,1987.0,22,tvSeries,-,-,6.7,53858.0,"Comedy,Drama,Family"
766,Rise of Empires: Ottoman,2020.0,44,tvMiniSeries,-,Turkish,7.9,19585.0,"Documentary,Drama,History"
1100,Human: The World Within,2021.0,\N,tvSeries,-,-,6.9,113.0,Documentary
1263,Selling Sunset,2019.0,30,tvSeries,-,-,6.3,3537.0,Reality-TV
...,...,...,...,...,...,...,...,...,...
6987,Criminal: Germany,2019.0,45,tvEpisode,-,German,8.1,611.0,"Crime,Drama,Mystery"
6991,Aggretsuko,2018.0,22,tvEpisode,-,-,7.5,235.0,"Animation,Comedy,Drama"
6995,Examen de conciencia,2019.0,\N,tvEpisode,-,English,8.5,13.0,"Crime,Documentary,History"
6998,True and the Rainbow Kingdom,2019.0,\N,tvEpisode,-,-,8.2,20.0,"Adventure,Animation,Family"
7005,Losers,2019.0,\N,tvEpisode,-,-,8.0,221.0,"Documentary,Sport"

In [14]:
# Drop a row orign_country rows with '-'
netflix1_df_dropcountry = netflix1_df_dropped_data[netflix1_df_dropped_data.orign_country != '-']
netflix1_df_dropcountry

,title,startYear,runtime,type,orign_country,language,rating,numVotes,genres
0,Lucifer,2016.0,42,tvSeries,United States,English,8.1,250884.0,"Crime,Drama,Fantasy"
1,Army of the Dead,2021.0,148,movie,United States,English,5.8,110780.0,"Action,Crime,Horror"
2,The Kominsky Method,2018.0,30,tvSeries,United States,English,8.2,28795.0,"Comedy,Drama"
3,Friends,1994.0,22,tvSeries,United States,English,8.9,861843.0,"Comedy,Romance"
4,Ragnarok,2020.0,45,tvSeries,Norway,Norwegian,7.5,26606.0,"Action,Drama,Fantasy"
...,...,...,...,...,...,...,...,...,...
7000,Team Kaylie,2019.0,\N,tvEpisode,United States,English,5.1,15.0,Comedy
7002,Ares,2020.0,32,tvEpisode,Netherlands,Dutch,6.5,191.0,"Drama,Horror,Mystery"
7003,Merry Happy Whatever,2019.0,28,tvEpisode,United States,English,6.1,221.0,Comedy
7006,Firefly Lane,2021.0,51,tvEpisode,United States,English,7.3,380.0,"Drama,Romance"
7007,Medical Police,2020.0,25,tvEpisode,United States,English,6.6,133.0,Comedy

In [15]:
#Look for the string "-" as Origin Country
netflix1_df_dropcountry[netflix1_df_dropcountry['language'].str.contains('-')]

,title,startYear,runtime,type,orign_country,language,rating,numVotes,genres
260,Narcos: México,2018.0,50,tvSeries,Mexico,-,8.4,63619.0,"Crime,Drama"
673,The Circle,2020.0,48,tvSeries,United States,-,7.3,4995.0,"Game-Show,Reality-TV"
1063,Boyka: Undisputed IV,2016.0,86,video,Bulgaria,-,7.0,26404.0,"Action,Drama,Sport"
1181,Then Came You,2018.0,97,movie,United States,-,7.0,10458.0,"Adventure,Comedy,Drama"
1183,Hap and Leonard,2016.0,60,tvSeries,United States,-,7.7,6913.0,"Crime,Drama,Mystery"
...,...,...,...,...,...,...,...,...,...
6779,The Punisher,2017.0,51,tvEpisode,United States,-,8.6,7346.0,"Action,Crime,Drama"
6830,Legend Quest,2017.0,\N,tvEpisode,France,-,6.8,25.0,"Adventure,Animation,Comedy"
6889,Cypher,2021.0,\N,tvEpisode,United States,-,7.4,50.0,"Action,Crime,Drama"
6939,Sirius the Jaeger,2018.0,\N,tvEpisode,Japan,-,7.5,53.0,"Action,Animation,History"
6990,Delhi Crime,2019.0,\N,tvEpisode,India,-,8.6,405.0,"Crime,Drama"

In [16]:
# Drop a row language rows with '-'
netflix1_df_droplanguage = netflix1_df_dropcountry[netflix1_df_dropcountry.language != '-']
netflix1_df_droplanguage

,title,startYear,runtime,type,orign_country,language,rating,numVotes,genres
0,Lucifer,2016.0,42,tvSeries,United States,English,8.1,250884.0,"Crime,Drama,Fantasy"
1,Army of the Dead,2021.0,148,movie,United States,English,5.8,110780.0,"Action,Crime,Horror"
2,The Kominsky Method,2018.0,30,tvSeries,United States,English,8.2,28795.0,"Comedy,Drama"
3,Friends,1994.0,22,tvSeries,United States,English,8.9,861843.0,"Comedy,Romance"
4,Ragnarok,2020.0,45,tvSeries,Norway,Norwegian,7.5,26606.0,"Action,Drama,Fantasy"
...,...,...,...,...,...,...,...,...,...
7000,Team Kaylie,2019.0,\N,tvEpisode,United States,English,5.1,15.0,Comedy
7002,Ares,2020.0,32,tvEpisode,Netherlands,Dutch,6.5,191.0,"Drama,Horror,Mystery"
7003,Merry Happy Whatever,2019.0,28,tvEpisode,United States,English,6.1,221.0,Comedy
7006,Firefly Lane,2021.0,51,tvEpisode,United States,English,7.3,380.0,"Drama,Romance"
7007,Medical Police,2020.0,25,tvEpisode,United States,English,6.6,133.0,Comedy

In [17]:
#Check all languages
all_languages = dict(netflix1_df_droplanguage['language'].value_counts())
print(all_languages)

{'English': 3346, 'Spanish': 389, 'Japanese': 364, 'Korean': 280, 'French': 153, 'Hindi': 147, 'Dutch': 102, 'Italian': 78, 'German': 73, 'Portuguese': 72, 'Mandarin': 66, 'Arabic': 60, 'Turkish': 58, 'Swedish': 58, 'Thai': 56, 'Indonesian': 49, 'Chinese': 30, 'Polish': 27, 'Norwegian': 21, 'Romanian': 19, 'Danish': 17, 'Russian': 14, 'Malay': 13, 'Cantonese': 12, 'Tagalog': 11, 'None': 10, 'Hebrew': 10, 'Malayalam': 10, 'Filipino': 9, 'Tamil': 9, 'Telugu': 9, 'Catalan': 7, 'Marathi': 6, 'Kannada': 5, 'Finnish': 5, 'Urdu': 5, 'Bengali': 4, 'Icelandic': 4, 'Hungarian': 4, 'Vietnamese': 3, 'Greek': 3, 'Georgian': 2, 'Latin': 2, 'Gujarati': 2, 'Punjabi': 2, 'Galician': 2, 'Akan': 2, 'Mongolian': 1, 'Brazilian Sign Language': 1, 'Basque': 1, 'Ukrainian': 1, 'Central Khmer': 1, 'Hausa': 1, 'Scanian': 1, 'Zulu': 1, 'Yiddish': 1, 'Persian': 1, 'Xhosa': 1, 'Wolof': 1, 'Greek, Ancient (to 1453)': 1, 'Ibo': 1, 'Yoruba': 1, 'Flemish': 1, 'American Sign Language': 1, 'Tswana': 1, 'Min Nan': 1, 'Luxembourgish': 1, 'Croatian': 1, 'Afrikaans': 1}

In [18]:
#Confirm all ratings contain a value by putting value counts into a dict then viewing dict
all_ratings = dict(netflix1_df_droplanguage['rating'].value_counts())
print(all_ratings)

{7.2: 236, 7.3: 202, 7.1: 191, 7.4: 191, 6.7: 191, 6.5: 188, 7.5: 185, 6.6: 184, 7.6: 184, 7.0: 183, 6.8: 178, 6.9: 175, 7.7: 174, 6.2: 166, 6.4: 161, 7.8: 156, 6.3: 149, 6.1: 136, 7.9: 125, 8.2: 122, 8.0: 122, 5.8: 118, 6.0: 117, 8.1: 114, 5.9: 114, 5.7: 112, 5.6: 111, 8.3: 103, 5.5: 94, 5.4: 92, 8.4: 76, 5.3: 71, 4.8: 68, 8.5: 68, 5.2: 67, 8.6: 61, 5.0: 52, 5.1: 46, 4.9: 45, 4.6: 44, 4.4: 43, 4.5: 39, 4.7: 39, 8.7: 34, 4.2: 27, 8.8: 26, 4.1: 23, 3.8: 22, 4.3: 21, 3.5: 20, 3.9: 18, 3.6: 17, 3.2: 15, 8.9: 15, 9.1: 13, 3.7: 13, 4.0: 12, 3.4: 11, 3.3: 10, 9.0: 10, 3.1: 6, 2.9: 5, 9.3: 5, 2.6: 5, 9.2: 5, 2.7: 5, 2.5: 4, 2.1: 3, 2.4: 3, 2.8: 2, 3.0: 2, 2.2: 2, 9.4: 2, 1.9: 1, 2.3: 1, 1.7: 1}

In [19]:
#Check all runtime
all_runtime = dict(netflix1_df_droplanguage['runtime'].value_counts())
print(all_runtime)

{'\\N': 605, '60': 265, '30': 162, '90': 152, '24': 146, '45': 124, '23': 98, '95': 86, '50': 86, '100': 84, '92': 81, '25': 78, '22': 77, '97': 76, '96': 74, '85': 73, '94': 73, '86': 70, '98': 68, '80': 67, '89': 65, '91': 64, '101': 64, '99': 64, '88': 62, '70': 62, '102': 58, '44': 56, '105': 56, '42': 54, '87': 53, '93': 52, '43': 51, '104': 50, '106': 49, '40': 47, '110': 45, '52': 43, '107': 41, '84': 41, '103': 41, '83': 40, '115': 40, '35': 38, '58': 38, '109': 37, '65': 37, '75': 37, '120': 37, '82': 36, '46': 36, '112': 36, '59': 34, '48': 34, '108': 34, '81': 34, '118': 33, '51': 31, '55': 31, '47': 30, '111': 30, '113': 30, '26': 27, '49': 26, '21': 25, '28': 25, '62': 24, '116': 24, '61': 24, '54': 24, '41': 23, '73': 23, '121': 23, '64': 23, '78': 23, '114': 21, '74': 21, '56': 20, '119': 20, '53': 20, '66': 20, '63': 20, '125': 20, '67': 19, '57': 19, '122': 19, '72': 19, '117': 18, '29': 18, '68': 17, '124': 17, '123': 17, '71': 17, '11': 17, '129': 17, '79': 17, '77': 16, '137': 15, '69': 15, '27': 14, '20': 14, '76': 14, '126': 13, '133': 13, '32': 13, '130': 12, '1': 11, '31': 11, '128': 10, '39': 10, '15': 10, '134': 9, '7': 9, '132': 9, '12': 9, '135': 9, '136': 9, '151': 8, '127': 8, '150': 8, '180': 8, '140': 8, '139': 7, '37': 7, '36': 7, '131': 6, '33': 6, '16': 6, '138': 5, '144': 5, '9': 5, '13': 5, '149': 5, '34': 5, '147': 4, '14': 4, '143': 4, '10': 4, '142': 4, '38': 4, '153': 4, '3': 4, '148': 4, '6': 3, '154': 3, '156': 3, '163': 3, '231': 3, '5': 3, '19': 3, '145': 3, '160': 3, '162': 3, '18': 3, '210': 2, '188': 2, '229': 2, '152': 2, '170': 2, '179': 2, '4': 2, '191': 2, '192': 2, '281': 2, '2': 2, '403': 2, '316': 2, '141': 2, '158': 2, '205': 2, '161': 2, '240': 2, '331': 2, '280': 2, '155': 2, '197': 2, '173': 1, '169': 1, '203': 1, '358': 1, '337': 1, '258': 1, '356': 1, '227': 1, '171': 1, '629': 1, '300': 1, '239': 1, '386': 1, '228': 1, '494': 1, '491': 1, '230': 1, '395': 1, '217': 1, '853': 1, '360': 1, '385': 1, '306': 1, '157': 1, '452': 1, '437': 1, '252': 1, '333': 1, '204': 1, '174': 1, '172': 1, '363': 1, '242': 1, '249': 1, '233': 1, '290': 1, '270': 1, '542': 1, '347': 1, '370': 1, '461': 1, '296': 1, '374': 1, '187': 1, '195': 1, '267': 1, '498': 1, '216': 1, '460': 1, '202': 1, '436': 1, '189': 1, '458': 1, '557': 1, '573': 1, '178': 1, '211': 1, '146': 1, '313': 1, '219': 1, '220': 1, '241': 1, '288': 1, '17': 1, '351': 1, '312': 1, '467': 1, '298': 1, '373': 1, '271': 1, '181': 1, '165': 1, '303': 1, '201': 1, '355': 1, '297': 1, '236': 1, '572': 1, '209': 1, '330': 1, '8': 1, '213': 1}

In [20]:
#Check values in type
netflix1_df_droplanguage.value_counts(['type'])

type
movie           2486
tvSeries        1760
tvEpisode        495
tvSpecial        340
tvMiniSeries     269
tvMovie          139
video             79
short             78
tvShort            5
videoGame          1
dtype: int64

In [21]:
#Look for the string "-" as Origin Country
netflix1_df_droplanguage[netflix1_df_droplanguage['type'].str.contains('video')]

,title,startYear,runtime,type,orign_country,language,rating,numVotes,genres
936,Sniper: Ghost Shooter,2016.0,99,video,United States,English,5.4,3277.0,"Action,Drama,Thriller"
1272,Sniper: Assassin's End,2020.0,95,video,United States,English,5.4,1510.0,"Action,Thriller"
1298,Tremors II: Aftershocks,1996.0,100,video,United States,English,6.0,27188.0,"Action,Comedy,Horror"
1385,The Scorpion King 3: Battle for Redemption,2012.0,105,video,United States,English,3.7,8059.0,"Action,Adventure,Fantasy"
1565,S.W.A.T.: Firefight,2011.0,89,video,United States,English,5.3,9653.0,"Action,Crime,Thriller"
...,...,...,...,...,...,...,...,...,...
6032,Graffiti Verité 2: Freedom of ExpreSSion?,1998.0,57,video,United States,English,6.2,5.0,"Documentary,History"
6172,Zoom In: Stories Behind the Best Independent F...,2007.0,61,video,United States,English,6.1,9.0,\N
6192,"A Decade of Decadence, Pt. 2: Legacy of Dreams",2013.0,65,video,United States,English,8.1,49.0,Documentary
6202,A Tiger in the Dark: The Decadence Saga,2014.0,128,video,United States,English,7.7,50.0,Drama
6215,Nohzdyve,2018.0,\N,videoGame,United States,English,7.5,6.0,Action

In [22]:
# Drop a row type rows with video game
netflix1_df_droptype = netflix1_df_droplanguage[netflix1_df_droplanguage.type != 'videoGame']
netflix1_df_droptype

,title,startYear,runtime,type,orign_country,language,rating,numVotes,genres
0,Lucifer,2016.0,42,tvSeries,United States,English,8.1,250884.0,"Crime,Drama,Fantasy"
1,Army of the Dead,2021.0,148,movie,United States,English,5.8,110780.0,"Action,Crime,Horror"
2,The Kominsky Method,2018.0,30,tvSeries,United States,English,8.2,28795.0,"Comedy,Drama"
3,Friends,1994.0,22,tvSeries,United States,English,8.9,861843.0,"Comedy,Romance"
4,Ragnarok,2020.0,45,tvSeries,Norway,Norwegian,7.5,26606.0,"Action,Drama,Fantasy"
...,...,...,...,...,...,...,...,...,...
7000,Team Kaylie,2019.0,\N,tvEpisode,United States,English,5.1,15.0,Comedy
7002,Ares,2020.0,32,tvEpisode,Netherlands,Dutch,6.5,191.0,"Drama,Horror,Mystery"
7003,Merry Happy Whatever,2019.0,28,tvEpisode,United States,English,6.1,221.0,Comedy
7006,Firefly Lane,2021.0,51,tvEpisode,United States,English,7.3,380.0,"Drama,Romance"
7007,Medical Police,2020.0,25,tvEpisode,United States,English,6.6,133.0,Comedy

In [23]:
#Set up replacement dictionary
replace_type = {"type": {"tvSeries": "tvShow",
                        "tvEpisode": "tvShow", 
                        "tvSpecial": "movie",
                        "tvMiniSeries": "tvShow",
                        "tvMovie": "movie",
                        "video": "movie",
                        "short": "movie",
                        "tvShort": "tvShow"
                         },  
               }

In [24]:
#Replace type so that all are movie or tvshow
netflix1_df_replacetype = netflix1_df_droptype.replace(replace_type)
netflix1_df_replacetype

,title,startYear,runtime,type,orign_country,language,rating,numVotes,genres
0,Lucifer,2016.0,42,tvShow,United States,English,8.1,250884.0,"Crime,Drama,Fantasy"
1,Army of the Dead,2021.0,148,movie,United States,English,5.8,110780.0,"Action,Crime,Horror"
2,The Kominsky Method,2018.0,30,tvShow,United States,English,8.2,28795.0,"Comedy,Drama"
3,Friends,1994.0,22,tvShow,United States,English,8.9,861843.0,"Comedy,Romance"
4,Ragnarok,2020.0,45,tvShow,Norway,Norwegian,7.5,26606.0,"Action,Drama,Fantasy"
...,...,...,...,...,...,...,...,...,...
7000,Team Kaylie,2019.0,\N,tvShow,United States,English,5.1,15.0,Comedy
7002,Ares,2020.0,32,tvShow,Netherlands,Dutch,6.5,191.0,"Drama,Horror,Mystery"
7003,Merry Happy Whatever,2019.0,28,tvShow,United States,English,6.1,221.0,Comedy
7006,Firefly Lane,2021.0,51,tvShow,United States,English,7.3,380.0,"Drama,Romance"
7007,Medical Police,2020.0,25,tvShow,United States,English,6.6,133.0,Comedy

In [25]:
#Check values in type
netflix1_df_replacetype.value_counts(['type'])

type
movie     3122
tvShow    2529
dtype: int64

In [26]:
#Check all genres
all_genres = dict(netflix1_df_replacetype['genres'].value_counts())
print(all_genres)

{'Comedy': 601, 'Documentary': 350, 'Drama': 341, 'Action,Adventure,Animation': 177, 'Comedy,Drama': 167, 'Drama,Romance': 135, 'Crime,Drama,Mystery': 127, 'Comedy,Drama,Romance': 117, 'Action,Crime,Drama': 117, 'Comedy,Romance': 107, 'Adventure,Animation,Comedy': 105, 'Reality-TV': 88, 'Crime,Drama,Thriller': 86, 'Comedy,Documentary': 68, 'Drama,Thriller': 66, 'Crime,Documentary': 65, 'Crime,Drama': 64, 'Action,Adventure,Drama': 63, 'Action,Crime,Thriller': 57, 'Comedy,Crime,Drama': 48, 'Animation': 45, 'Action,Adventure,Comedy': 44, 'Drama,Mystery,Thriller': 42, 'Horror': 42, 'Horror,Thriller': 42, 'Thriller': 41, 'Drama,Fantasy,Horror': 40, 'Action,Animation,Comedy': 40, 'Drama,Horror,Mystery': 37, 'Action,Adventure,Crime': 37, 'Documentary,Short': 35, 'Animation,Comedy,Family': 33, 'Documentary,Music': 32, 'Documentary,Sport': 32, 'Action,Comedy,Crime': 31, 'Comedy,Drama,Family': 29, 'Animation,Comedy,Drama': 29, 'Biography,Drama,History': 29, 'Romance': 28, 'Documentary,History': 25, 'Drama,Mystery,Sci-Fi': 25, 'Biography,Drama': 24, 'Adventure,Animation,Family': 24, 'Action,Animation,Fantasy': 24, 'Biography,Documentary': 24, 'Action,Animation,Drama': 24, 'Drama,Horror,Thriller': 24, 'Action': 23, 'Animation,Family': 22, 'Comedy,Family': 22, 'Action,Drama,Thriller': 22, 'Crime': 21, 'Biography,Crime,Drama': 21, 'Action,Thriller': 21, 'Horror,Mystery,Thriller': 20, 'Comedy,Drama,Fantasy': 20, 'Action,Comedy,Drama': 19, 'Comedy,Horror': 18, 'Adventure,Animation,Drama': 18, 'Action,Adventure,Fantasy': 18, 'Family': 18, 'Action,Adventure,Sci-Fi': 17, 'Drama,Mystery,Romance': 17, 'Drama,History': 17, 'Adventure,Comedy,Drama': 17, 'Crime,Documentary,History': 17, 'Mystery,Thriller': 16, 'Action,Drama,Fantasy': 16, 'Action,Drama': 16, 'Drama,Fantasy,Mystery': 16, 'Animation,Comedy': 16, 'Drama,Mystery': 15, 'Comedy,Music': 15, 'Biography,Documentary,History': 15, 'Drama,Sci-Fi': 15, 'Crime,Drama,Fantasy': 14, 'Comedy,Fantasy,Romance': 14, 'Documentary,Drama': 14, 'Action,Comedy': 14, 'Drama,Music,Romance': 14, 'Drama,Sci-Fi,Thriller': 13, 'Drama,Family': 13, 'Action,Drama,History': 13, 'Comedy,Crime': 13, 'Action,Animation,Sci-Fi': 12, 'Biography,Documentary,Drama': 12, 'Comedy,Drama,Music': 12, 'Action,Drama,Sci-Fi': 12, 'Biography,Documentary,Music': 12, 'Crime,Drama,Horror': 12, 'Drama,Fantasy': 11, 'Crime,Thriller': 11, 'Drama,Sport': 11, 'Drama,Fantasy,Romance': 11, 'Crime,Drama,Romance': 11, 'Game-Show,Reality-TV': 11, 'Drama,History,Romance': 11, 'Documentary,Reality-TV': 11, 'Biography,Comedy,Drama': 10, 'Animation,Drama,Family': 10, 'Crime,Documentary,Mystery': 10, 'Animation,Comedy,Romance': 10, 'Biography,Documentary,Sport': 10, 'Adventure,Drama,Mystery': 10, 'Action,Animation,Crime': 10, 'Animation,Drama,Fantasy': 10, 'Biography,Crime,Documentary': 10, 'Drama,Horror,Sci-Fi': 9, 'Talk-Show': 9, 'Crime,Mystery,Thriller': 9, 'Animation,Comedy,Fantasy': 9, '\\N': 9, 'Comedy,Reality-TV': 9, 'Adventure,Drama,Fantasy': 8, 'Biography,Drama,Romance': 8, 'Action,Adventure,Family': 8, 'Animation,Short': 7, 'Adventure,Comedy,Crime': 7, 'Animation,Drama,Romance': 7, 'Crime,Documentary,Drama': 7, 'Action,Comedy,Fantasy': 7, 'Crime,Drama,Film-Noir': 7, 'Game-Show': 7, 'Action,Crime': 7, 'Adventure,Comedy,Family': 7, 'Adventure,Drama,Family': 7, 'Music': 6, 'Biography,Drama,Sport': 6, 'Adventure,Drama,History': 6, 'Comedy,Drama,Horror': 6, 'Horror,Mystery': 6, 'Drama,Romance,Sci-Fi': 6, 'Drama,Romance,Thriller': 6, 'Drama,History,War': 6, 'Documentary,History,War': 6, 'Drama,History,Thriller': 6, 'Adventure,Biography,Drama': 6, 'Biography,Drama,Music': 6, 'Animation,Family,Fantasy': 6, 'Documentary,Drama,Family': 6, 'Adventure,Drama': 6, 'Sci-Fi,Thriller': 6, 'Drama,Horror': 6, 'Action,Biography,Drama': 6, 'Drama,Music': 6, 'Comedy,Family,Romance': 5, 'Western': 5, 'Horror,Sci-Fi,Thriller': 5, 'Fantasy,Romance': 5, 'Comedy,Short': 5, 'Comedy,Sci-Fi': 5, 'Action,Drama,Romance': 5, 'Comedy,Family,Fantasy': 5, 'Action,Adventure,Thriller': 5, 'Comedy,Talk-Show': 5, 'Documentary,War': 5, 'Action,Drama,Horror': 5, 'Comedy,Documentary,Drama': 5, 'Comedy,Thriller': 5, 'Action,Crime,Mystery': 5, 'Action,Sci-Fi': 5, 'Comedy,Drama,Sci-Fi': 5, 'Drama,Reality-TV': 5, 'Drama,Western': 5, 'Adventure,Animation,Fantasy': 5, 'Action,Horror,Thriller': 5, 'Drama,Musical': 4, 'Fantasy,Mystery,Romance': 4, 'Documentary,History,News': 4, 'Biography': 4, 'Action,Comedy,Romance': 4, 'Adventure,Documentary': 4, 'Adventure': 4, 'Comedy,Fantasy,Horror': 4, 'Drama,War': 4, 'Action,Mystery,Thriller': 4, 'Horror,Mystery,Sci-Fi': 4, 'News': 4, 'Comedy,Crime,Mystery': 4, 'Animation,Comedy,Sport': 4, 'Action,Sci-Fi,Thriller': 4, 'Comedy,Fantasy': 4, 'Action,Comedy,Family': 4, 'Action,Fantasy,Sci-Fi': 4, 'Comedy,Family,Musical': 4, 'Drama,Thriller,War': 4, 'Animation,Sport': 4, 'Comedy,Sport': 4, 'Documentary,Short,Sport': 4, 'Comedy,Drama,Thriller': 4, 'Family,Fantasy,Musical': 4, 'Sci-Fi': 4, 'Action,Adventure,Biography': 4, 'Adventure,Fantasy,Horror': 4, 'Action,Horror,Sci-Fi': 4, 'Music,Reality-TV': 4, 'Comedy,Musical': 4, 'Reality-TV,Romance': 4, 'Drama,Family,Romance': 4, 'Drama,Family,Fantasy': 4, 'Action,Drama,Mystery': 4, 'Documentary,News': 4, 'Crime,Horror,Mystery': 4, 'Drama,Family,Music': 3, 'Adventure,Comedy,Fantasy': 3, 'Comedy,Crime,Thriller': 3, 'Action,Drama,War': 3, 'Action,Fantasy,Horror': 3, 'Action,Animation': 3, 'Fantasy,Horror,Mystery': 3, 'Animation,Drama,Music': 3, 'Adventure,Comedy': 3, 'Fantasy': 3, 'Horror,Short': 3, 'Romance,Sci-Fi': 3, 'Action,Drama,Sport': 3, 'Action,Crime,Sci-Fi': 3, 'Biography,Documentary,News': 3, 'Fantasy,Horror': 3, 'Family,Fantasy': 3, 'Animation,Crime,Drama': 3, 'Action,Adventure,Mystery': 3, 'Action,Adventure': 3, 'Drama,Music,Musical': 3, 'Animation,Fantasy': 3, 'Animation,Drama,Short': 3, 'Drama,Fantasy,Sci-Fi': 3, 'Short': 3, 'Comedy,Drama,Musical': 3, 'Biography,Drama,War': 3, 'Horror,Reality-TV': 3, 'Comedy,Musical,Romance': 3, 'Drama,Short': 3, 'Action,Crime,Fantasy': 3, 'Comedy,Drama,Sport': 3, 'Adventure,Animation': 3, 'Biography,Comedy,Documentary': 3, 'Crime,Documentary,Sport': 3, 'Adventure,Documentary,Drama': 3, 'Comedy,Documentary,History': 3, 'Documentary,Talk-Show': 3, 'Biography,Documentary,Short': 3, 'Biography,Documentary,Family': 3, 'Documentary,Family': 3, 'Animation,Drama,Horror': 3, 'Comedy,Horror,Reality-TV': 3, 'Comedy,Horror,Thriller': 3, 'Crime,History,Thriller': 3, 'Documentary,Drama,History': 3, 'Drama,Horror,Music': 2, 'Action,Biography,Crime': 2, 'Adventure,Reality-TV': 2, 'Action,Animation,Horror': 2, 'Family,Fantasy,Horror': 2, 'Drama,Romance,Sport': 2, 'Drama,Fantasy,Thriller': 2, 'Crime,Drama,History': 2, 'Documentary,Drama,Sport': 2, 'Documentary,Mystery': 2, 'Action,Romance,Thriller': 2, 'Action,Horror': 2, 'Animation,Comedy,Documentary': 2, 'Animation,Family,Short': 2, 'Mystery,Sci-Fi,Thriller': 2, 'Comedy,Drama,War': 2, 'Action,Comedy,History': 2, 'Biography,History,War': 2, 'Adventure,Family,Fantasy': 2, 'Biography,History': 2, 'Action,Thriller,War': 2, 'Action,Adventure,Horror': 2, 'Sport': 2, 'Crime,Documentary,Music': 2, 'Action,Fantasy,Mystery': 2, 'Animation,Drama,Mystery': 2, 'Animation,Documentary': 2, 'Music,Romance': 2, 'Comedy,Music,Romance': 2, 'Animation,Family,Musical': 2, 'Adventure,Drama,Romance': 2, 'Adventure,Drama,Horror': 2, 'Adventure,Comedy,Romance': 2, 'Adventure,Fantasy,Romance': 2, 'Adventure,Sci-Fi': 2, 'Crime,Drama,Sci-Fi': 2, 'Adventure,Horror,Thriller': 2, 'Comedy,Drama,Mystery': 2, 'Mystery': 2, 'Action,Comedy,Sci-Fi': 2, 'Documentary,Game-Show': 2, 'Comedy,Fantasy,Musical': 2, 'Fantasy,Horror,Sci-Fi': 2, 'Action,Biography,Documentary': 2, 'Comedy,Drama,Western': 2, 'Adventure,Drama,Thriller': 2, 'Comedy,Music,Short': 2, 'Horror,Sci-Fi': 2, 'Comedy,Mystery': 2, 'Action,Romance': 2, 'Drama,History,Sport': 2, 'Crime,Horror,Thriller': 2, 'Action,Animation,Sport': 2, 'Action,Horror,Mystery': 2, 'Animation,Drama,Sport': 2, 'Comedy,History,Romance': 2, 'Documentary,Horror': 2, 'Drama,Romance,War': 2, 'Drama,Family,Sci-Fi': 2, 'Crime,Drama,Music': 2, 'Documentary,Drama,Short': 2, 'Horror,Mystery,Romance': 2, 'Action,Comedy,Horror': 2, 'Comedy,Horror,Romance': 2, 'Action,Western': 2, 'Comedy,Music,Musical': 2, 'Biography,Documentary,Romance': 2, 'Animation,Horror': 2, 'Adventure,Animation,Sci-Fi': 2, 'Game-Show,Music': 2, 'Comedy,Family,Sci-Fi': 1, 'Fantasy,Horror,Thriller': 1, 'Crime,Drama,Western': 1, 'Adventure,Music,Sci-Fi': 1, 'Animation,Documentary,Sci-Fi': 1, 'Family,Reality-TV': 1, 'Music,Musical': 1, 'Action,Documentary,History': 1, 'Action,Mystery': 1, 'Animation,Fantasy,Sci-Fi': 1, 'Biography,Crime': 1, 'Adventure,Animation,Short': 1, 'Action,Drama,Western': 1, 'Family,Music': 1, 'Documentary,History,Mystery': 1, 'Adventure,Drama,Sci-Fi': 1, 'Documentary,Music,Sport': 1, 'Action,War': 1, 'Horror,Romance': 1, 'Drama,Family,Horror': 1, 'Comedy,Short,Talk-Show': 1, 'Action,Adventure,War': 1, 'Documentary,Romance': 1, 'Drama,Sci-Fi,Short': 1, 'Documentary,Reality-TV,Sport': 1, 'Adventure,Family': 1, 'Family,Romance': 1, 'Crime,Horror': 1, 'Family,Game-Show': 1, 'Adventure,Documentary,News': 1, 'Drama,Family,Mystery': 1, 'Adventure,Biography,Documentary': 1, 'Biography,Music': 1, 'Documentary,History,Short': 1, 'Fantasy,Thriller': 1, 'Crime,Mystery,Romance': 1, 'Comedy,Romance,Sci-Fi': 1, 'Documentary,Western': 1, 'Comedy,Fantasy,Reality-TV': 1, 'Comedy,Family,Music': 1, 'Action,Biography,History': 1, 'Drama,Family,Reality-TV': 1, 'Animation,Biography,Drama': 1, 'Action,History': 1, 'Action,Comedy,Thriller': 1, 'Documentary,Sci-Fi,Short': 1, 'Adventure,Documentary,Game-Show': 1, 'Adventure,Fantasy,Sci-Fi': 1, 'Adventure,Fantasy': 1, 'Drama,Family,History': 1, 'Drama,Thriller,Western': 1, 'Action,Crime,Romance': 1, 'Action,Crime,Documentary': 1, 'Animation,Musical': 1, 'Biography,Documentary,War': 1, 'Comedy,Crime,Family': 1, 'Horror,Music,Thriller': 1, 'Family,Music,Romance': 1, 'Game-Show,Reality-TV,Romance': 1, 'Adventure,Drama,Sport': 1, 'Crime,Sci-Fi,Thriller': 1, 'Biography,Drama,Mystery': 1, 'Drama,History,Western': 1, 'Musical': 1, 'Animation,Comedy,Short': 1, 'Comedy,Crime,Western': 1, 'Drama,Film-Noir,Mystery': 1, 'Adventure,Documentary,History': 1, 'Adventure,Animation,Horror': 1, 'Action,Adventure,Documentary': 1, 'Animation,Documentary,History': 1, 'Biography,Drama,Thriller': 1, 'Action,Fantasy,Thriller': 1, 'Comedy,Crime,Romance': 1, 'Crime,Fantasy,Thriller': 1, 'Adventure,Thriller': 1, 'Drama,Family,Sport': 1, 'Crime,Fantasy,Mystery': 1, 'Comedy,Romance,Sport': 1, 'Comedy,News,Talk-Show': 1, 'Fantasy,Mystery': 1, 'Film-Noir,Thriller': 1, 'Documentary,Reality-TV,Romance': 1, 'Adventure,Comedy,Reality-TV': 1, 'Horror,Mystery,Short': 1, 'Action,Animation,Family': 1, 'History,Sport,Thriller': 1, 'Music,Short': 1, 'Crime,Documentary,News': 1, 'Action,Fantasy,History': 1, 'Action,Comedy,War': 1, 'Action,Mystery,Romance': 1, 'Family,Short': 1, 'Comedy,Family,Horror': 1, 'Documentary,History,Sport': 1, 'Comedy,Mystery,Romance': 1, 'Crime,Documentary,Thriller': 1, 'Documentary,Mystery,Reality-TV': 1, 'Crime,Film-Noir,Mystery': 1, 'Action,Crime,Horror': 1, 'Musical,Romance': 1, 'Drama,History,Music': 1, 'Action,Romance,Sci-Fi': 1, 'Documentary,Drama,Fantasy': 1, 'Comedy,Romance,Western': 1, 'Documentary,Horror,Mystery': 1, 'Documentary,Family,Short': 1, 'Drama,Fantasy,History': 1, 'Fantasy,Horror,Romance': 1, 'Documentary,Drama,Mystery': 1, 'Adventure,Mystery': 1, 'Comedy,Documentary,Musical': 1, 'Adventure,Comedy,Mystery': 1, 'Crime,Drama,Family': 1, 'Comedy,Documentary,Music': 1, 'Action,Adventure,Sport': 1, 'Animation,Fantasy,Romance': 1, 'Animation,Comedy,Musical': 1, 'Crime,Documentary,Short': 1, 'Documentary,Short,War': 1, 'Comedy,Fantasy,Mystery': 1, 'Biography,Drama,Family': 1, 'Game-Show,Reality-TV,Sport': 1, 'Family,Sport': 1, 'Adventure,Drama,War': 1, 'Action,Animation,History': 1, 'Drama,Horror,Romance': 1, 'Fantasy,Music': 1, 'Crime,Film-Noir,Thriller': 1, 'Comedy,Fantasy,Short': 1, 'Documentary,Reality-TV,Talk-Show': 1, 'Comedy,Horror,Mystery': 1, 'Game-Show,Horror,Reality-TV': 1, 'War': 1, 'Action,Animation,Romance': 1, 'Drama,Family,Musical': 1, 'Animation,Family,Sci-Fi': 1, 'Biography,Comedy': 1, 'Animation,Comedy,Sci-Fi': 1, 'Animation,Mystery,Short': 1, 'Biography,Thriller': 1, 'Crime,Mystery,Sci-Fi': 1, 'Mystery,Sci-Fi,Short': 1, 'Game-Show,Music,Reality-TV': 1, 'Family,Musical': 1, 'Action,Fantasy,Western': 1, 'Comedy,Drama,History': 1}

In [27]:
#Split genres into 3 columns
netflix1_df_replacetype[['Genre1','Genre2','Genre3']] = netflix1_df_replacetype["genres"].str.split(',', expand=True)
netflix1_df_replacetype.head()

,title,startYear,runtime,type,orign_country,language,rating,numVotes,genres,Genre1,Genre2,Genre3
0,Lucifer,2016.0,42,tvShow,United States,English,8.1,250884.0,"Crime,Drama,Fantasy",Crime,Drama,Fantasy
1,Army of the Dead,2021.0,148,movie,United States,English,5.8,110780.0,"Action,Crime,Horror",Action,Crime,Horror
2,The Kominsky Method,2018.0,30,tvShow,United States,English,8.2,28795.0,"Comedy,Drama",Comedy,Drama,None
3,Friends,1994.0,22,tvShow,United States,English,8.9,861843.0,"Comedy,Romance",Comedy,Romance,None
4,Ragnarok,2020.0,45,tvShow,Norway,Norwegian,7.5,26606.0,"Action,Drama,Fantasy",Action,Drama,Fantasy

In [28]:
netflix1_df_clean = netflix1_df_replacetype.drop(columns=['genres'])
netflix1_df_clean

,title,startYear,runtime,type,orign_country,language,rating,numVotes,Genre1,Genre2,Genre3
0,Lucifer,2016.0,42,tvShow,United States,English,8.1,250884.0,Crime,Drama,Fantasy
1,Army of the Dead,2021.0,148,movie,United States,English,5.8,110780.0,Action,Crime,Horror
2,The Kominsky Method,2018.0,30,tvShow,United States,English,8.2,28795.0,Comedy,Drama,None
3,Friends,1994.0,22,tvShow,United States,English,8.9,861843.0,Comedy,Romance,None
4,Ragnarok,2020.0,45,tvShow,Norway,Norwegian,7.5,26606.0,Action,Drama,Fantasy
...,...,...,...,...,...,...,...,...,...,...,...
7000,Team Kaylie,2019.0,\N,tvShow,United States,English,5.1,15.0,Comedy,None,None
7002,Ares,2020.0,32,tvShow,Netherlands,Dutch,6.5,191.0,Drama,Horror,Mystery
7003,Merry Happy Whatever,2019.0,28,tvShow,United States,English,6.1,221.0,Comedy,None,None
7006,Firefly Lane,2021.0,51,tvShow,United States,English,7.3,380.0,Drama,Romance,None
7007,Medical Police,2020.0,25,tvShow,United States,English,6.6,133.0,Comedy,None,None

#Start on Netflix2 DataFrame

In [29]:
netflix2_df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [30]:
netflix2_df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [31]:
#Drop unused Columns
netflix2_df_dropped = netflix2_df.drop(columns=['director','description','cast','listed_in','show_id'])
netflix2_df_dropped.head()

,type,title,country,date_added,release_year,rating,duration
0,Movie,Dick Johnson Is Dead,United States,"September 25, 2021",2020,PG-13,90 min
1,TV Show,Blood & Water,South Africa,"September 24, 2021",2021,TV-MA,2 Seasons
2,TV Show,Ganglands,NaN,"September 24, 2021",2021,TV-MA,1 Season
3,TV Show,Jailbirds New Orleans,NaN,"September 24, 2021",2021,TV-MA,1 Season
4,TV Show,Kota Factory,India,"September 24, 2021",2021,TV-MA,2 Seasons

In [32]:
#Count number of entries in each column
netflix2_df_dropped.count()

type            8807
title           8807
country         7976
date_added      8797
release_year    8807
rating          8803
duration        8804
dtype: int64

In [33]:
#Check for null columns
netflix2_df_dropped.isnull().sum()

type              0
title             0
country         831
date_added       10
release_year      0
rating            4
duration          3
dtype: int64

In [34]:
#Check for null columns in duration
netflix2_df_dropped[netflix2_df_dropped['duration'].isnull()]

,type,title,country,date_added,release_year,rating,duration
5541,Movie,Louis C.K. 2017,United States,"April 4, 2017",2017,74 min,NaN
5794,Movie,Louis C.K.: Hilarious,United States,"September 16, 2016",2010,84 min,NaN
5813,Movie,Louis C.K.: Live at the Comedy Store,United States,"August 15, 2016",2015,66 min,NaN

In [35]:
#Check for null columns in date_added
netflix2_df_dropped[netflix2_df_dropped['date_added'].isnull()]

,type,title,country,date_added,release_year,rating,duration
6066,TV Show,A Young Doctor's Notebook and Other Stories,United Kingdom,NaN,2013,TV-MA,2 Seasons
6174,TV Show,Anthony Bourdain: Parts Unknown,United States,NaN,2018,TV-PG,5 Seasons
6795,TV Show,Frasier,United States,NaN,2003,TV-PG,11 Seasons
6806,TV Show,Friends,United States,NaN,2003,TV-14,10 Seasons
6901,TV Show,Gunslinger Girl,Japan,NaN,2008,TV-14,2 Seasons
7196,TV Show,Kikoriki,NaN,NaN,2010,TV-Y,2 Seasons
7254,TV Show,La Familia P. Luche,United States,NaN,2012,TV-14,3 Seasons
7406,TV Show,Maron,United States,NaN,2016,TV-MA,4 Seasons
7847,TV Show,Red vs. Blue,United States,NaN,2015,NR,13 Seasons
8182,TV Show,The Adventures of Figaro Pho,Australia,NaN,2015,TV-Y7,2 Seasons

In [36]:
#Rename rating column
netflix2_df_rename = netflix2_df_dropped.rename(columns={"rating": "Movie Rating"})
netflix2_df_rename

,type,title,country,date_added,release_year,Movie Rating,duration
0,Movie,Dick Johnson Is Dead,United States,"September 25, 2021",2020,PG-13,90 min
1,TV Show,Blood & Water,South Africa,"September 24, 2021",2021,TV-MA,2 Seasons
2,TV Show,Ganglands,NaN,"September 24, 2021",2021,TV-MA,1 Season
3,TV Show,Jailbirds New Orleans,NaN,"September 24, 2021",2021,TV-MA,1 Season
4,TV Show,Kota Factory,India,"September 24, 2021",2021,TV-MA,2 Seasons
...,...,...,...,...,...,...,...
8802,Movie,Zodiac,United States,"November 20, 2019",2007,R,158 min
8803,TV Show,Zombie Dumb,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons
8804,Movie,Zombieland,United States,"November 1, 2019",2009,R,88 min
8805,Movie,Zoom,United States,"January 11, 2020",2006,PG,88 min
8806,Movie,Zubaan,India,"March 2, 2019",2015,TV-14,111 min

In [37]:
#Drop rows with missing data
netflix2_df_dropped_data = netflix2_df_rename.dropna(subset=['country','date_added','Movie Rating','duration'])
netflix2_df_dropped_data

,type,title,country,date_added,release_year,Movie Rating,duration
0,Movie,Dick Johnson Is Dead,United States,"September 25, 2021",2020,PG-13,90 min
1,TV Show,Blood & Water,South Africa,"September 24, 2021",2021,TV-MA,2 Seasons
4,TV Show,Kota Factory,India,"September 24, 2021",2021,TV-MA,2 Seasons
7,Movie,Sankofa,"United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min
8,TV Show,The Great British Baking Show,United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons
...,...,...,...,...,...,...,...
8801,Movie,Zinzana,"United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min
8802,Movie,Zodiac,United States,"November 20, 2019",2007,R,158 min
8804,Movie,Zombieland,United States,"November 1, 2019",2009,R,88 min
8805,Movie,Zoom,United States,"January 11, 2020",2006,PG,88 min
8806,Movie,Zubaan,India,"March 2, 2019",2015,TV-14,111 min

In [38]:
#Check all countries of origin
all_languages2 = dict(netflix2_df_dropped_data['country'].value_counts())
print(all_languages2)

{'United States': 2809, 'India': 972, 'United Kingdom': 418, 'Japan': 243, 'South Korea': 199, 'Canada': 181, 'Spain': 145, 'France': 124, 'Mexico': 110, 'Egypt': 106, 'Turkey': 105, 'Nigeria': 95, 'Australia': 85, 'Taiwan': 81, 'Indonesia': 79, 'Brazil': 77, 'United Kingdom, United States': 75, 'Philippines': 75, 'United States, Canada': 73, 'Germany': 67, 'China': 66, 'Thailand': 61, 'Argentina': 56, 'Hong Kong': 53, 'United States, United Kingdom': 47, 'Canada, United States': 45, 'Italy': 44, 'Colombia': 35, 'South Africa': 30, 'France, Belgium': 27, 'Poland': 24, 'Singapore': 23, 'Malaysia': 22, 'Netherlands': 19, 'Pakistan': 18, 'United States, Germany': 17, 'United States, Japan': 16, 'United States, France': 16, 'Hong Kong, China': 16, 'Lebanon': 15, 'Russia': 15, 'United Arab Emirates': 14, 'Chile': 14, 'United States, Mexico': 14, 'China, Hong Kong': 14, 'Denmark': 13, 'Sweden': 13, 'Mexico, United States': 13, 'Australia, United States': 13, 'Israel': 13, 'Germany, United States': 13, 'New Zealand': 12, 'Japan, United States': 12, 'United States, Australia': 11, 'Norway': 11, 'India, United States': 10, 'Ireland': 10, 'France, United States': 10, 'Belgium': 9, 'United States, India': 9, 'Argentina, Spain': 8, 'Saudi Arabia': 8, 'United Kingdom, Canada, United States': 8, 'United States, China': 8, 'United States, France, Japan': 7, 'Vietnam': 7, 'South Korea, United States': 6, 'Romania': 6, 'United Kingdom, France': 6, 'Kuwait': 6, 'Italy, France': 5, 'United States, Czech Republic': 5, 'United States, New Zealand': 5, 'Spain, France': 5, 'Iceland': 5, 'India, France': 5, 'United States, Italy': 5, 'Israel, United States': 5, 'Austria': 5, 'United Kingdom, Canada': 4, 'Poland, United States': 4, 'Peru': 4, 'United States, Bulgaria': 4, 'United States, Russia': 4, 'Mexico, Spain': 4, 'United States, Spain': 4, 'Canada, United States, United Kingdom': 4, 'Hong Kong, United States': 4, 'Italy, United States': 4, 'United Kingdom, United States, Spain, Germany, Greece, Canada': 4, 'United States, United Kingdom, Australia': 4, 'United States, United Kingdom, France': 4, 'South Africa, United States': 4, 'United Kingdom, Germany': 4, 'Hungary': 4, 'United Kingdom, France, United States': 4, 'United States, South Africa': 3, 'Ghana': 3, 'Denmark, United States': 3, 'Kenya': 3, 'United States, United Arab Emirates': 3, 'Spain, Germany': 3, 'China, Canada, United States': 3, 'Belgium, France': 3, 'United Kingdom, United States, Australia': 3, 'United States, Colombia': 3, 'Bulgaria, United States': 3, 'United States, Ireland': 3, 'United Kingdom, Japan, United States': 3, 'Sweden, United States': 3, 'United States, Chile': 3, 'United States, Hong Kong': 3, 'Spain, Argentina': 3, 'Uruguay': 3, 'France, Egypt': 3, 'Bangladesh': 3, 'United States, Germany, Canada': 3, 'France, Canada': 3, 'United States, Sweden': 3, 'United Kingdom, Ireland': 3, 'China, United Kingdom': 3, 'Lebanon, Canada, France': 2, 'India, United Kingdom': 2, 'Norway, Iceland, United States': 2, 'United States, Japan, Canada': 2, 'United Kingdom, India': 2, 'China, Taiwan': 2, 'United Kingdom, Belgium': 2, 'Indonesia, Singapore': 2, 'United States, Argentina': 2, 'Spain, United Kingdom': 2, 'United Arab Emirates, United States': 2, 'Canada, South Africa': 2, 'Canada, United Kingdom': 2, 'Canada, United States, France': 2, 'United States, United Kingdom, Canada': 2, 'United Kingdom,': 2, 'Ireland, United Kingdom': 2, 'Canada, India': 2, 'Thailand, United States': 2, 'Argentina, Chile': 2, 'Canada, United Kingdom, United States': 2, 'Netherlands, Belgium': 2, 'Portugal, Spain': 2, 'Ireland, United Kingdom, United States': 2, 'Colombia, Mexico, United States': 2, 'Australia, Canada': 2, 'Spain, Italy': 2, 'Canada, Australia': 2, 'Belgium, Netherlands': 2, 'United States, Thailand': 2, 'United Kingdom, India, United States': 2, 'India, Soviet Union': 2, 'United Kingdom, Italy': 2, 'Brazil, France': 2, 'China, United States': 2, 'United States, South Korea': 2, 'Ukraine': 2, 'United Kingdom, Germany, United States': 2, 'Serbia, United States': 2, 'United States, United Kingdom, Germany': 2, 'Australia, United Kingdom': 2, 'France, United Kingdom, United States': 2, 'United Kingdom, Nigeria': 2, 'Czech Republic, United States': 2, 'United States, China, Hong Kong': 2, 'Singapore, United States': 2, 'France, Japan, United States': 2, 'Jordan': 2, 'United States, South Korea, China': 2, 'United Kingdom, France, Germany, United States': 2, 'Australia, United Arab Emirates': 2, 'United States, Greece': 2, 'Switzerland': 2, 'Spain, Mexico': 2, 'Germany, Czech Republic': 2, 'Turkey, United States': 2, 'India, Germany': 2, 'New Zealand, United States': 2, 'United Kingdom, United States, France': 2, 'Germany, United Kingdom': 2, 'Hong Kong, China, United States': 2, 'Egypt, France': 2, 'United States, Nigeria': 2, 'Pakistan, United States': 2, 'United States, United Kingdom, Denmark, Sweden': 1, 'United States, France, Canada, Belgium': 1, 'France, Brazil, Spain, Belgium': 1, 'Taiwan, China, France, United States': 1, 'United Kingdom, Canada, Japan': 1, 'United Kingdom, Spain, United States': 1, 'South Africa, United States, New Zealand, Canada': 1, 'France, Senegal, Belgium': 1, 'United Kingdom, France, United States, Belgium, Luxembourg, China, Germany': 1, 'United States, United Kingdom, Germany, Hungary': 1, 'Argentina, Uruguay, Spain, France': 1, 'Poland, West Germany': 1, 'Israel, Sweden, Germany, Netherlands': 1, 'Australia, India': 1, 'Romania, United Kingdom': 1, 'Austria, Germany': 1, 'United Kingdom, West Germany': 1, 'Denmark, France, Poland': 1, 'India, Germany, France': 1, 'South Africa, Angola': 1, 'United States, Hungary, Ireland, Canada': 1, 'United States, Germany, United Kingdom, Italy': 1, 'India, United Kingdom, China, Canada, Japan, South Korea, United States': 1, 'United Kingdom, Namibia, South Africa, Zimbabwe, United States': 1, 'France, Israel, Germany, United States, United Kingdom': 1, 'France, Canada, Italy, United States, China': 1, 'Italy, Belgium': 1, 'Peru, United States, United Kingdom': 1, 'Australia, Iraq': 1, 'Australia, Armenia, Japan, Jordan, Mexico, Mongolia, New Zealand, Philippines, South Africa, Sweden, United States, Uruguay': 1, 'Germany, United States, Canada': 1, 'Switzerland, France, Belgium, United States': 1, 'Mexico, Argentina': 1, 'France, Iran, United States': 1, 'Georgia': 1, 'China, United States, Canada': 1, 'Ireland, France, Iceland, United States, Mexico, Belgium, United Kingdom, Hong Kong': 1, 'France, Netherlands, South Africa, Finland': 1, 'France, United Kingdom': 1, 'Spain, France, United States': 1, 'Germany, Jordan, Netherlands': 1, 'Syria, France, Lebanon, Qatar': 1, 'United Kingdom, Australia': 1, 'Mexico, Brazil': 1, 'Luxembourg': 1, 'United Kingdom, France, Germany, Spain': 1, 'France, Belgium, Luxembourg, Cambodia,': 1, 'Canada, France, Italy, Morocco, United States': 1, 'Denmark, Indonesia, Finland, Norway, United Kingdom, Israel, France, United States, Germany, Netherlands': 1, 'United Arab Emirates, United Kingdom, India': 1, 'Turkey, India': 1, 'Chile, Brazil': 1, 'Uruguay, Argentina, Spain': 1, 'United Kingdom, Norway, Denmark, Germany, Sweden': 1, 'South Africa, Nigeria': 1, 'United States, East Germany, West Germany': 1, 'Italy, France, Switzerland': 1, 'United Kingdom, France, Belgium, Canada, United States': 1, 'China, India, Nepal': 1, 'France, United Kingdom, India': 1, 'Spain, France, United Kingdom, United States': 1, 'United Kingdom, Australia, France': 1, 'Spain, France, Uruguay': 1, 'United Kingdom, Germany, France, United States': 1, 'United Kingdom, China, United States': 1, 'Brazil, Netherlands, United States, Colombia, Austria, Germany': 1, 'Lebanon, United Arab Emirates, France, Switzerland, Germany': 1, 'United States, Belgium, Canada, France': 1, 'France, Luxembourg, United States': 1, 'Romania, Bulgaria, Hungary': 1, 'Ireland, Canada': 1, 'France, Belgium, China, United States': 1, 'Czech Republic, United Kingdom, France': 1, 'India, Nepal': 1, 'Ireland, Canada, Luxembourg, United States, United Kingdom, Philippines, India': 1, 'Uruguay, Germany': 1, 'Puerto Rico, United States, Colombia': 1, 'Mexico, United States, Spain, Colombia': 1, 'Senegal': 1, 'Egypt, Saudi Arabia': 1, 'Canada, Spain': 1, 'France, Germany, Czech Republic, Belgium': 1, 'Netherlands, Belgium, United Kingdom, United States': 1, 'Egypt, Austria, United States': 1, 'United States, India, Bangladesh': 1, 'United Kingdom, Poland, United States': 1, 'Chile, Italy': 1, 'Pakistan, United Arab Emirates': 1, 'United States, Greece, Brazil': 1, 'Hong Kong, Taiwan': 1, 'China, South Korea, United States': 1, 'United States, Germany, United Kingdom': 1, 'Canada, United States, Denmark': 1, 'United States, Mexico, Spain, Malta': 1, 'South Korea, China, United States': 1, 'United Kingdom, Ireland, United States': 1, 'Ireland, United Kingdom, Italy, United States': 1, 'United Kingdom, Malawi': 1, 'United States, France, Mexico': 1, 'Soviet Union, India': 1, 'Denmark, United Kingdom, Sweden': 1, 'Germany, United States, Italy': 1, 'Spain, Mexico, France': 1, 'India, Japan': 1, 'Hungary, United States': 1, 'France, South Korea, Japan': 1, 'Mexico, France, Colombia': 1, 'France, Germany, Switzerland': 1, 'United States, Italy, Romania, United Kingdom': 1, 'Italy, United Kingdom, France': 1, 'Finland, Sweden, Norway, Latvia, Germany': 1, 'Canada, France': 1, 'Spain, Canada, United States': 1, 'United States, Canada, Japan, Panama': 1, 'United Kingdom, United States, Dominican Republic': 1, 'United Kingdom, South Korea': 1, 'South Korea, France': 1, 'Saudi Arabia, Syria, Egypt, Lebanon, Kuwait': 1, 'Italy, Turkey': 1, 'Denmark, Singapore, Canada, United States': 1, 'Canada, Luxembourg': 1, 'United States, France, United Kingdom, Japan': 1, 'Mozambique': 1, 'Denmark, France, United States, Sweden': 1, 'United States, Philippines': 1, 'United Kingdom, Australia, United States': 1, 'Croatia': 1, 'United States, India, South Korea, China': 1, 'Spain, United Kingdom, United States': 1, 'Germany, France, Luxembourg, United Kingdom, United States': 1, 'Canada, Nigeria': 1, 'Germany, United States, Hong Kong, Singapore': 1, 'United States, South Korea, Japan': 1, 'Czech Republic, United Kingdom, United States': 1, 'Ireland, United Kingdom, Greece, France, Netherlands': 1, 'United States,': 1, 'United States, Brazil': 1, 'Italy, United Kingdom': 1, 'Philippines, Canada, United Kingdom, United States': 1, 'United Arab Emirates, Jordan, Lebanon, Saudi Arabia': 1, 'Mexico, Netherlands': 1, 'United States, United Kingdom, Morocco': 1, 'Thailand, China, United States': 1, 'Norway, Germany': 1, 'Norway, Germany, Sweden': 1, 'Norway, Denmark': 1, 'Italy, Switzerland, Albania, Poland': 1, 'Indonesia, United States': 1, 'India, United Kingdom, France, Qatar': 1, 'United Arab Emirates, Romania': 1, 'Lebanon, United Arab Emirates': 1, 'United States, Bermuda, Ecuador': 1, 'United States, Czech Republic, United Kingdom': 1, 'Uruguay, Argentina, Germany, Spain': 1, 'Saudi Arabia, United Arab Emirates': 1, 'Canada, United States, Mexico': 1, 'United States, France, Canada': 1, 'Denmark, France, Belgium, Italy, Netherlands, United States, United Kingdom': 1, 'Canada, Mexico, Germany, South Africa': 1, 'Australia, New Zealand, United States': 1, 'Canada, India, Thailand, United States, United Arab Emirates': 1, 'Spain, Portugal': 1, 'Argentina, France': 1, 'Canada, Germany, France, United States': 1, 'Italy, Canada, France': 1, 'Ireland, Canada, United Kingdom, United States': 1, 'United Kingdom, Lithuania': 1, 'France, Algeria': 1, 'Australia, United Kingdom, United States, New Zealand, Italy, France': 1, 'United States, United Kingdom, France, Germany, Japan': 1, 'Egypt, Algeria': 1, 'Germany, United States, Sweden': 1, 'Bulgaria': 1, 'United States, Australia, Mexico': 1, 'India, Pakistan': 1, 'Venezuela': 1, 'China, United States, Australia': 1, 'Canada, Japan, United States': 1, 'United States, Canada, Belgium, United Kingdom': 1, 'France, Morocco': 1, 'Argentina, Chile, Peru': 1, 'United States, Netherlands, Japan, France': 1, 'South Africa, United States, Germany': 1, 'France, Canada, United States, Spain': 1, 'Netherlands, United States': 1, 'Denmark, Germany, Belgium, United Kingdom, France': 1, 'United Kingdom, Canada, France, United States': 1, 'France, Lebanon, United Kingdom': 1, 'France, Canada, Belgium': 1, 'New Zealand, United Kingdom': 1, 'United States, Denmark': 1, 'United Kingdom, France, Belgium': 1, 'Finland, France': 1, 'Spain, Italy, Argentina': 1, 'Cambodia': 1, 'Turkey, South Korea': 1, 'Spain, Switzerland': 1, 'Belarus': 1, 'United Kingdom, Germany, United States, France': 1, 'Japan, Canada, United States': 1, 'United States, Morocco': 1, 'France, New Zealand': 1, 'United States, Poland': 1, 'France, Qatar': 1, 'Denmark, Spain': 1, 'Croatia, Slovenia, Serbia, Montenegro': 1, 'India, Mexico': 1, 'Chile, Spain, Argentina, Germany': 1, 'Netherlands, Denmark, South Africa': 1, 'Italy, South Africa, West Germany, Australia, United States': 1, 'United Kingdom, China': 1, 'India, United Kingdom, Canada, United States': 1, 'United Kingdom, Australia, Canada, United States': 1, 'Philippines, Singapore': 1, 'United States, Taiwan': 1, 'South Korea, Japan': 1, 'Belgium, Ireland, Netherlands, Germany, Afghanistan': 1, 'United Kingdom, Japan': 1, 'United Kingdom, Poland': 1, 'Denmark, Brazil, France, Portugal, Sweden': 1, 'Israel, Germany': 1, 'Denmark, United Kingdom, South Africa, Sweden, Belgium': 1, 'Hong Kong, China, Singapore': 1, 'South Africa, Germany, Netherlands, France': 1, 'Zimbabwe': 1, 'United Kingdom, Denmark, Canada, Croatia': 1, 'India, Germany, Austria': 1, 'Colombia, Mexico': 1, 'Indonesia, South Korea, Singapore': 1, 'United Kingdom, Hungary, Australia': 1, 'France, Belgium, Italy': 1, 'Singapore, Japan, France': 1, 'Somalia, Kenya, Sudan, South Africa, United States': 1, 'United Arab Emirates, United States, United Kingdom': 1, 'Italy, Germany': 1, 'Uruguay, Argentina': 1, 'China, Hong Kong, United States': 1, 'United Kingdom, Singapore': 1, 'United States, Singapore': 1, 'Russia, Spain': 1, 'United Kingdom, China, United States, India': 1, 'Canada, France, United States': 1, 'United States, Chile, Israel': 1, 'Nigeria, United Kingdom': 1, 'United Kingdom, Spain, Belgium': 1, ', South Korea': 1, 'United States, United Kingdom, India': 1, 'United States, China, United Kingdom': 1, 'Norway, Sweden': 1, 'Canada, Brazil': 1, 'Iran, France': 1, 'Spain, United States': 1, 'Spain, Belgium': 1, 'Taiwan, Malaysia': 1, 'France, South Korea, Japan, United States': 1, 'Kuwait, United States': 1, 'Chile, Argentina, France, Spain, United States': 1, 'United Kingdom, United States, Czech Republic': 1, 'Germany, Australia, France, China': 1, 'France, Netherlands, Singapore': 1, 'United Kingdom, France, Spain, United States': 1, 'Brazil, United Kingdom': 1, 'Germany, France': 1, 'Switzerland, France': 1, 'United Kingdom, Canada, United States, Cayman Islands': 1, 'United States, France, South Korea, Indonesia': 1, 'Canada, Nigeria, United States': 1, 'France, United States, Mexico': 1, 'Chile, Argentina': 1, 'Netherlands, Denmark, France, Germany': 1, 'Finland': 1, 'Turkey, Azerbaijan': 1, 'Canada, Norway': 1, 'Norway, United States': 1, 'Canada, Germany, South Africa': 1, 'United States, Ireland, United Kingdom, India': 1, 'South Korea, Czech Republic': 1, 'Russia, United States': 1, 'France, Belgium, United States': 1, 'Switzerland, United Kingdom, Australia': 1, 'United Kingdom, United States, Germany, Denmark, Belgium, Japan': 1, 'France, Lebanon': 1, 'Canada, Ireland, United States': 1, 'United Kingdom, Pakistan': 1, 'Australia, France': 1, 'United States, Canada, Indonesia, United Kingdom, China, Singapore': 1, 'United States, India, United Kingdom': 1, 'Uruguay, Spain, Mexico': 1, 'France, Luxembourg, Canada': 1, 'United Kingdom, Belgium, Sweden': 1, 'Taiwan, Hong Kong, United States, China': 1, 'France, Canada, China, Cambodia': 1, 'Switzerland, United Kingdom, United States': 1, 'Canada, United Kingdom, Netherlands': 1, 'Sweden, Czech Republic, United Kingdom, Denmark, Netherlands': 1, 'Argentina, Venezuela': 1, 'Germany, France, Russia': 1, 'Chile, Peru': 1, 'Spain, Thailand, United States': 1, 'Chile, France': 1, 'Germany, Canada, United States': 1, 'United States, Ghana, Burkina Faso, United Kingdom, Germany, Ethiopia': 1, 'China, Germany, India, United States': 1, 'Belgium, France, Netherlands': 1, 'Australia, France, Ireland': 1, 'United States, France, Denmark': 1, 'Germany, Australia': 1, 'United Kingdom, France, Belgium, United States': 1, 'Germany, France, United States, Canada, United Kingdom': 1, 'Japan, Canada': 1, 'New Zealand, Australia, France, United States': 1, 'Singapore, France': 1, 'Israel, Germany, Poland, Luxembourg, Belgium, France, United States': 1, 'Canada, United States, Ireland': 1, 'India, Canada': 1, 'Hong Kong, Canada, United States': 1, 'United Kingdom, Russia': 1, 'United Kingdom, India, Sweden': 1, 'Turkey, France, Germany, Poland': 1, 'Germany, Belgium': 1, 'United Kingdom, Italy, Israel, Peru, United States': 1, 'United Kingdom, New Zealand': 1, 'Italy, Switzerland, France, Germany': 1, 'Germany, United States, France': 1, 'United Kingdom, France, Germany': 1, 'Cyprus': 1, 'Germany, United Kingdom, United States': 1, 'Canada, United States, India, United Kingdom': 1, 'Bulgaria, United States, Spain, Canada': 1, 'United Kingdom, Australia, France, United States': 1, 'United States, Iceland': 1, 'Mexico, Finland': 1, 'Norway, Denmark, Netherlands, Sweden': 1, 'Canada, Germany': 1, 'Netherlands, Belgium, Germany, Jordan': 1, 'Ireland, United Kingdom, France, Germany': 1, 'New Zealand, United Kingdom, Australia': 1, 'United States, United Kingdom, New Zealand': 1, ', France, Algeria': 1, 'United Kingdom, France, United States, Belgium': 1, 'United Arab Emirates, Jordan': 1, 'United Kingdom, Germany, Spain, United States': 1, 'Indonesia, United Kingdom': 1, 'Egypt, Denmark, Germany': 1, 'Canada, Japan, Netherlands': 1, 'Lebanon, United States, United Arab Emirates': 1, 'United States, Canada, Germany': 1, 'Ireland, United States, United Kingdom': 1, 'Lebanon, Palestine, Denmark, Qatar': 1, 'United Kingdom, France, Canada, Belgium, United States': 1, 'Ireland, Luxembourg, Belgium': 1, 'United States, New Zealand, United Kingdom': 1, 'Namibia': 1, 'France, Australia, Germany': 1, 'Spain, Cuba': 1, 'United States, United Kingdom, Italy': 1, 'United Kingdom, Spain, United States, Germany': 1, 'Spain, France, Canada, United States': 1, 'Ireland, United States': 1, 'Argentina, United States, Mexico': 1, 'United Kingdom, Canada, Italy': 1, 'United States, Brazil, Japan, Spain, India': 1, 'United States, Canada, China': 1, 'Philippines, United States': 1, 'United States, Cambodia': 1, 'United Kingdom, Jordan, Qatar, Iran': 1, 'United Kingdom, Russia, United States': 1, 'United States, France, Serbia': 1, 'France, United States, United Kingdom, Canada': 1, 'United Kingdom, United States, Japan': 1, 'Canada, Spain, France': 1, 'United States, United Kingdom, Spain, South Korea': 1, 'Austria, Czech Republic': 1, 'Russia, Poland, Serbia': 1, 'United States, India, United Arab Emirates': 1, 'Jamaica, United States': 1, 'Hong Kong, Iceland, United States': 1, 'United Kingdom, Germany, Canada, United States': 1, 'West Germany': 1, 'India, Australia': 1, 'United Kingdom, Czech Republic, United States, Germany, Bahamas': 1, 'Sweden, Netherlands': 1, 'Argentina, Brazil, France, Poland, Germany, Denmark': 1, 'United States, Uruguay': 1, 'Ghana, United States': 1, 'United States, Cambodia, Romania': 1, 'South Africa, United States, Japan': 1, 'United Kingdom, Ukraine, United States': 1, 'Indonesia, Netherlands': 1, 'South Korea, Canada, United States, China': 1, 'Argentina, United States': 1, 'Portugal, France, Poland, United States': 1, 'Denmark, Sweden, Israel, United States': 1, 'Portugal, United 

In [39]:
#Check all movie_ratings
all_releases = dict(netflix2_df_dropped_data['Movie Rating'].value_counts())
print(all_releases)

{'TV-MA': 2929, 'TV-14': 1927, 'R': 788, 'TV-PG': 771, 'PG-13': 482, 'PG': 281, 'TV-Y7': 235, 'TV-Y': 227, 'TV-G': 190, 'NR': 79, 'G': 41, 'TV-Y7-FV': 5, 'UR': 3, 'NC-17': 3}

In [40]:
#Set up rating replacement dictionary
replace_rating = {"Movie Rating": {"TV-MA": "adult",
                        "TV-14": "teen", 
                        "R": "adult",
                        "TV-PG": "children",
                        "PG-13": "teen",
                        "PG": "children",        
                        "TV-Y7": "children",
                        "TV-Y": "children",
                        "TV-G": "children",
                        "NR": "adult",
                        "G": "children",
                        "TV-Y7-FV": "children",
                        "NC-17": "adult",
                        "UR": "adult",
                         },  
               }

In [41]:
#Replace rating so that all are binned into adult, children, or teen 
netflix2_df_replacerating = netflix2_df_dropped_data.replace(replace_rating)
netflix2_df_replacerating

,type,title,country,date_added,release_year,Movie Rating,duration
0,Movie,Dick Johnson Is Dead,United States,"September 25, 2021",2020,teen,90 min
1,TV Show,Blood & Water,South Africa,"September 24, 2021",2021,adult,2 Seasons
4,TV Show,Kota Factory,India,"September 24, 2021",2021,adult,2 Seasons
7,Movie,Sankofa,"United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,adult,125 min
8,TV Show,The Great British Baking Show,United Kingdom,"September 24, 2021",2021,teen,9 Seasons
...,...,...,...,...,...,...,...
8801,Movie,Zinzana,"United Arab Emirates, Jordan","March 9, 2016",2015,adult,96 min
8802,Movie,Zodiac,United States,"November 20, 2019",2007,adult,158 min
8804,Movie,Zombieland,United States,"November 1, 2019",2009,adult,88 min
8805,Movie,Zoom,United States,"January 11, 2020",2006,children,88 min
8806,Movie,Zubaan,India,"March 2, 2019",2015,teen,111 min

In [42]:
#Check all durations
all_types = dict(netflix2_df_replacerating['duration'].value_counts())
print(all_types)

{'1 Season': 1456, '2 Seasons': 383, '3 Seasons': 187, '90 min': 147, '94 min': 141, '93 min': 139, '97 min': 138, '95 min': 135, '91 min': 134, '92 min': 123, '96 min': 120, '102 min': 117, '98 min': 113, '99 min': 112, '88 min': 110, '101 min': 110, '103 min': 109, '106 min': 104, '100 min': 103, '89 min': 102, '104 min': 102, '86 min': 98, '105 min': 97, '87 min': 95, '110 min': 92, '4 Seasons': 92, '107 min': 90, '108 min': 83, '116 min': 76, '112 min': 73, '109 min': 69, '85 min': 69, '113 min': 66, '83 min': 65, '111 min': 64, '5 Seasons': 63, '119 min': 62, '118 min': 62, '117 min': 60, '81 min': 59, '84 min': 59, '115 min': 56, '120 min': 53, '114 min': 53, '121 min': 52, '124 min': 51, '82 min': 48, '127 min': 48, '126 min': 42, '123 min': 41, '128 min': 41, '78 min': 40, '122 min': 40, '80 min': 40, '130 min': 40, '133 min': 39, '132 min': 36, '135 min': 36, '137 min': 36, '75 min': 35, '125 min': 34, '79 min': 33, '6 Seasons': 33, '129 min': 32, '131 min': 31, '72 min': 30, '74 min': 30, '71 min': 26, '77 min': 26, '73 min': 26, '61 min': 26, '76 min': 25, '60 min': 24, '66 min': 24, '70 min': 24, '143 min': 23, '53 min': 23, '140 min': 23, '136 min': 23, '134 min': 22, '63 min': 22, '46 min': 22, '54 min': 22, '69 min': 22, '7 Seasons': 22, '139 min': 20, '24 min': 20, '59 min': 20, '62 min': 19, '58 min': 19, '148 min': 19, '52 min': 19, '141 min': 18, '150 min': 17, '68 min': 16, '64 min': 16, '44 min': 16, '145 min': 16, '8 Seasons': 16, '67 min': 16, '149 min': 15, '138 min': 15, '151 min': 15, '65 min': 15, '57 min': 13, '55 min': 13, '40 min': 13, '142 min': 13, '154 min': 12, '158 min': 12, '162 min': 12, '153 min': 11, '163 min': 11, '147 min': 11, '146 min': 11, '22 min': 11, '156 min': 10, '51 min': 10, '56 min': 10, '155 min': 10, '144 min': 9, '29 min': 9, '161 min': 9, '47 min': 9, '50 min': 8, '165 min': 8, '28 min': 8, '25 min': 8, '9 Seasons': 8, '45 min': 8, '42 min': 8, '168 min': 7, '171 min': 6, '32 min': 6, '157 min': 6, '166 min': 6, '33 min': 6, '26 min': 6, '10 Seasons': 6, '49 min': 6, '152 min': 5, '185 min': 5, '160 min': 5, '176 min': 5, '173 min': 5, '48 min': 5, '30 min': 5, '23 min': 4, '159 min': 4, '177 min': 4, '172 min': 4, '38 min': 4, '170 min': 4, '164 min': 4, '35 min': 3, '17 min': 3, '14 min': 3, '181 min': 3, '27 min': 3, '41 min': 3, '31 min': 2, '13 min': 2, '12 min': 2, '12 Seasons': 2, '174 min': 2, '209 min': 2, '169 min': 2, '20 min': 2, '15 Seasons': 2, '192 min': 2, '13 Seasons': 2, '195 min': 2, '15 min': 2, '21 min': 2, '187 min': 2, '180 min': 2, '179 min': 2, '5 min': 1, '186 min': 1, '3 min': 1, '208 min': 1, '18 min': 1, '43 min': 1, '167 min': 1, '17 Seasons': 1, '178 min': 1, '16 min': 1, '203 min': 1, '253 min': 1, '193 min': 1, '11 Seasons': 1, '205 min': 1, '10 min': 1, '182 min': 1, '36 min': 1, '224 min': 1, '237 min': 1, '8 min': 1, '37 min': 1, '196 min': 1, '200 min': 1, '312 min': 1, '191 min': 1, '214 min': 1, '189 min': 1, '228 min': 1, '19 min': 1, '194 min': 1, '201 min': 1, '9 min': 1, '229 min': 1, '190 min': 1}

In [43]:
#Drop country, date_added, and duration
netflix2_df_dropped_2 = netflix2_df_replacerating.drop(columns=['country','date_added','duration'])
netflix2_df_dropped_2.head()

      type                          title  release_year Movie Rating
0    Movie           Dick Johnson Is Dead          2020         teen
1  TV Show                  Blood & Water          2021        adult
4  TV Show                   Kota Factory          2021        adult
7    Movie                        Sankofa          1993        adult
8  TV Show  The Great British Baking Show          2021         teen

In [44]:
## LG
# Changed netflix1_df_clean types to align with netflix2_df_replacerating type names
netflix1_df_clean.type.unique()
netflix1_df_clean['type'].replace(['tvShow'],['TV Show'],inplace=True)
netflix1_df_clean['type'].replace(['movie'],['Movie'],inplace=True)
netflix1_df_clean.head()

,title,startYear,runtime,type,orign_country,language,rating,numVotes,Genre1,Genre2,Genre3
0,Lucifer,2016.0,42,TV Show,United States,English,8.1,250884.0,Crime,Drama,Fantasy
1,Army of the Dead,2021.0,148,Movie,United States,English,5.8,110780.0,Action,Crime,Horror
2,The Kominsky Method,2018.0,30,TV Show,United States,English,8.2,28795.0,Comedy,Drama,None
3,Friends,1994.0,22,TV Show,United States,English,8.9,861843.0,Comedy,Romance,None
4,Ragnarok,2020.0,45,TV Show,Norway,Norwegian,7.5,26606.0,Action,Drama,Fantasy

In [45]:
netflix1_df_clean.dtypes

title             object
startYear        float64
runtime           object
type              object
orign_country     object
language          object
rating           float64
numVotes         float64
Genre1            object
Genre2            object
Genre3            object
dtype: object

In [46]:
netflix2_df_dropped_2.dtypes

type            object
title           object
release_year     int64
Movie Rating    object
dtype: object

In [47]:
# Converting startYear (N1) from float to integer 
netflix1_df_clean['startYear'] = netflix1_df_clean['startYear'].astype(int)
netflix1_df_clean.dtypes
netflix1_df_clean.head()

,title,startYear,runtime,type,orign_country,language,rating,numVotes,Genre1,Genre2,Genre3
0,Lucifer,2016,42,TV Show,United States,English,8.1,250884.0,Crime,Drama,Fantasy
1,Army of the Dead,2021,148,Movie,United States,English,5.8,110780.0,Action,Crime,Horror
2,The Kominsky Method,2018,30,TV Show,United States,English,8.2,28795.0,Comedy,Drama,None
3,Friends,1994,22,TV Show,United States,English,8.9,861843.0,Comedy,Romance,None
4,Ragnarok,2020,45,TV Show,Norway,Norwegian,7.5,26606.0,Action,Drama,Fantasy

In [48]:
# Converting numVotes (N1) from float to integer 
netflix1_df_clean['numVotes'] = netflix1_df_clean['numVotes'].astype(int)
netflix1_df_clean.head()

,title,startYear,runtime,type,orign_country,language,rating,numVotes,Genre1,Genre2,Genre3
0,Lucifer,2016,42,TV Show,United States,English,8.1,250884,Crime,Drama,Fantasy
1,Army of the Dead,2021,148,Movie,United States,English,5.8,110780,Action,Crime,Horror
2,The Kominsky Method,2018,30,TV Show,United States,English,8.2,28795,Comedy,Drama,None
3,Friends,1994,22,TV Show,United States,English,8.9,861843,Comedy,Romance,None
4,Ragnarok,2020,45,TV Show,Norway,Norwegian,7.5,26606,Action,Drama,Fantasy

In [49]:
# Reviewing the NA's.. what are the chances Genre2 & Genre3 will skew the results since they're null?
netflix1_df_clean.isna().sum()

title               0
startYear           0
runtime             0
type                0
orign_country       0
language            0
rating              0
numVotes            0
Genre1              0
Genre2           1662
Genre3           3087
dtype: int64

In [50]:
# Viewing unique values in "Genre1" column Nextfix1
netflix1_df_clean.Genre1.unique()

array(['Crime', 'Action', 'Comedy', 'Drama', 'Adventure', 'Animation',
       'Biography', 'Horror', 'Mystery', 'Musical', 'Family', 'Game-Show',
       'Reality-TV', 'Documentary', 'Thriller', 'Sci-Fi', 'Fantasy',
       'History', 'Romance', 'Sport', 'Talk-Show', 'Music', 'Film-Noir',
       'Western', 'War', '\\N', 'News', 'Short'], dtype=object)

In [51]:
# Deleting "\\N" from Genre 1
netflix1_df_clean = netflix1_df_clean.loc[netflix1_df_clean["Genre1"] != "\\N"]

In [52]:
# Viewing updated unique values in "Genre1" column Nextfix1
netflix1_df_clean.Genre1.unique()

array(['Crime', 'Action', 'Comedy', 'Drama', 'Adventure', 'Animation',
       'Biography', 'Horror', 'Mystery', 'Musical', 'Family', 'Game-Show',
       'Reality-TV', 'Documentary', 'Thriller', 'Sci-Fi', 'Fantasy',
       'History', 'Romance', 'Sport', 'Talk-Show', 'Music', 'Film-Noir',
       'Western', 'War', 'News', 'Short'], dtype=object)

In [53]:
# Deleting "\\N" from Genre 2
netflix1_df_clean = netflix1_df_clean.loc[netflix1_df_clean["Genre2"] != "\\N"]

In [54]:
# Deleting "\\N" from Genre 3 
netflix1_df_clean = netflix1_df_clean.loc[netflix1_df_clean["Genre3"] != "\\N"]

In [55]:
# Viewing unique values in "Genre3" column Nextfix1
netflix1_df_clean.Genre3.unique()

array(['Fantasy', 'Horror', None, 'Drama', 'Mystery', 'Thriller', 'Music',
       'Comedy', 'Romance', 'Animation', 'Crime', 'History', 'Sci-Fi',
       'Biography', 'Sport', 'Family', 'Musical', 'War', 'Western',
       'Reality-TV', 'Short', 'Film-Noir', 'Documentary', 'Talk-Show',
       'Game-Show', 'News'], dtype=object)

In [56]:
#Rename columns for N1 for formatting 
netflix1_df_renamed = netflix1_df_clean.rename(columns={"title": "Title", 
                                                        "startYear": "Start Year", 
                                                       "runtime": "Run Time",
                                                       "type": "Type",
                                                       "orign_country": "Origin Country",
                                                       "language": "Language",
                                                       "rating": "Rating",
                                                       "numVotes": "Number of Votes",
                                                       })
netflix1_df_renamed

,Title,Start Year,Run Time,Type,Origin Country,Language,Rating,Number of Votes,Genre1,Genre2,Genre3
0,Lucifer,2016,42,TV Show,United States,English,8.1,250884,Crime,Drama,Fantasy
1,Army of the Dead,2021,148,Movie,United States,English,5.8,110780,Action,Crime,Horror
2,The Kominsky Method,2018,30,TV Show,United States,English,8.2,28795,Comedy,Drama,None
3,Friends,1994,22,TV Show,United States,English,8.9,861843,Comedy,Romance,None
4,Ragnarok,2020,45,TV Show,Norway,Norwegian,7.5,26606,Action,Drama,Fantasy
...,...,...,...,...,...,...,...,...,...,...,...
7000,Team Kaylie,2019,\N,TV Show,United States,English,5.1,15,Comedy,None,None
7002,Ares,2020,32,TV Show,Netherlands,Dutch,6.5,191,Drama,Horror,Mystery
7003,Merry Happy Whatever,2019,28,TV Show,United States,English,6.1,221,Comedy,None,None
7006,Firefly Lane,2021,51,TV Show,United States,English,7.3,380,Drama,Romance,None
7007,Medical Police,2020,25,TV Show,United States,English,6.6,133,Comedy,None,None

In [57]:
#Rename columns for N2 for formatting 
netflix2_df_renamed = netflix2_df_dropped_2.rename(columns={"type": "Type", 
                                                       "title": "Title",
                                                       "release_year": "Release Year",
                                                       })
netflix2_df_renamed

         Type                          Title  Release Year Movie Rating
0       Movie           Dick Johnson Is Dead          2020         teen
1     TV Show                  Blood & Water          2021        adult
4     TV Show                   Kota Factory          2021        adult
7       Movie                        Sankofa          1993        adult
8     TV Show  The Great British Baking Show          2021         teen
...       ...                            ...           ...          ...
8801    Movie                        Zinzana          2015        adult
8802    Movie                         Zodiac          2007        adult
8804    Movie                     Zombieland          2009        adult
8805    Movie                           Zoom          2006     children
8806    Movie                         Zubaan          2015         teen

[7961 rows x 4 columns]

In [66]:
#Export cleaned DF1 to CSV file
netflix1_df_renamed.to_csv('../Netflix_Team_1/Resources/netflix1clean.csv', index=False)

In [67]:
# Export cleaned DF2 to CSV file
netflix2_df_renamed.to_csv('../Netflix_Team_1/Resources/netflix2clean.csv', index=False)

In [68]:
#Create merged dataframe
joined_df = pd.merge(netflix1_df_renamed, netflix2_df_renamed, how='inner', left_on=['Title', 'Type'], right_on=['Title','Type'])
joined_df

,Title,Start Year,Run Time,Type,Origin Country,Language,Rating,Number of Votes,Genre1,Genre2,Genre3,Release Year,Movie Rating
0,Lucifer,2016,42,TV Show,United States,English,8.1,250884,Crime,Drama,Fantasy,2021,teen
1,Army of the Dead,2021,148,Movie,United States,English,5.8,110780,Action,Crime,Horror,2021,adult
2,The Kominsky Method,2018,30,TV Show,United States,English,8.2,28795,Comedy,Drama,None,2021,adult
3,Ragnarok,2020,45,TV Show,Norway,Norwegian,7.5,26606,Action,Drama,Fantasy,2021,adult
4,StartUp,2016,44,TV Show,United States,English,8.0,16980,Crime,Thriller,None,2018,adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2221,Fakkah Fuzz: Almost Banned,2018,60,Movie,Singapore,English,4.2,40,Comedy,None,None,2018,adult
2222,Dieter Nuhr: Nuhr in Berlin,2016,69,Movie,Germany,German,4.6,65,Comedy,None,None,2016,adult
2223,Fernando Sanjiao: Hombre,2018,\N,Movie,Argentina,Spanish,6.3,55,Comedy,None,None,2018,adult
2224,Saverio Raimondo: Il Satiro Parlante,2019,53,Movie,Italy,Italian,6.0,42,Comedy,None,None,2019,adult
2225,Sam Kinison: The Scream Continues,2016,29,Movie,United States,English,6.4,57,Documentary,Short,None,2016,adult

In [69]:
# Export merged to CSV file
joined_df.to_csv('../Netflix_Team_1/Resources/joined.csv', index=False)